# Generated by Django 5.2.4 on 2025-07-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_id', models.CharField(max_length=100, unique=True)),
                ('Order_name', models.CharField(max_length=100)),
                ('User_id', models.CharField(max_length=100, unique=True)),
                ('Placed_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
