# Generated by Django 5.2.4 on 2025-07-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
